services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uroot -ppassword
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "rm -f tmp/pids/server.pid && ./bin/dev"
    volumes:
      - .:/test_app
      - node_modules:/test_app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - db
      - selenium_chrome
  selenium_chrome:
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444
volumes:
  mysql_data:
  node_modules: